host-name: 0.0.0.0
transfer-timeout: 800
mongodb: mongodb://mongodb:27017
redis-url: redis://redis:6379
velocity-secret: Y6QivRnJvqe7
require-auth: false
sandbox: false
spark: false
anticheat: false
redis-uri: redis://redis:6379
limbo:
    host-name: 127.0.0.1
    port: 65535
integrations:
    spark: false
    anticheat: false
    via-version: false
    sentry-dsn: ''
resource-packs: {}
